name: Deploy to Firebase Hosting

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Yarn CLI
        uses: CultureHQ/actions-yarn@v1.0.1
      - name: Install Deps
        run: yarn
      - name: Build
        run: yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CODE_HEROES }}'
          channelId: live
          projectId: code-heroes
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
